
paths:
  input_data: data/llm_output/pred_with_raw.jsonl
  raw_data: data/raw_data/test.json
  prompt: ../data/prompt/prompt.txt
  output_dir: output/
  generated_code_dir: output/generated_code/
model:
  type: deepseek-chat
  api_key: sk-07a5ae9fd7744216b6bf26209fd1b5cc
  base_url: https://api.deepseek.com/v1
  temperature: 0.0
metrics:
  - mae
  - ice
logging:
  level: INFO
  file: output/logs/evaluation.log