
paths:
  raw_llm: data/raw_llm/qwen_7b没微调的结果.jsonl
  llm_with_data: data/llm_with_data/qwen_7b没微调的结果_with_data.json
  llm_with_data_code: data/llm_with_data_code/qwen_7b没微调的结果_with_data_code.json
  generated_predictions: data/llm_output/pred_with_raw.jsonl
  prompt: ../data/prompt/prompt.txt
  prompt_raw: ../data/prompt/prompt_with_raw.txt
  output_dir: output/results/
  generated_data_dir: data/llm_with_data/
  generated_code_dir: data/llm_with_data_code/
model:
  type: deepseek-chat
  api_key: sk-07a5ae9fd7744216b6bf26209fd1b5cc
  base_url: https://api.deepseek.com/v1
  temperature: 0.0
metrics:
  - mae
  - ice
logging:
  level: INFO
  file: ../output/logs/evaluation.log